nodeLinker: node-modules

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
      spec: "@yarnpkg/plugin-interactive-tools"
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: "@yarnpkg/plugin-typescript"
    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
      spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs

packageExtensions:
    revolt.js@*:
        dependencies:
            typescript: "^5.4.5"
    "@revoltchat/ui@*":
        dependencies:
            typescript: "^5.4.5"
